export const vendorsData = [
  { name: "Orbita", status: "active", label: "Orbita" },
  { name: "Kant", status: "active", label: "Kant" },
  { name: "Diplomat", status: "active", label: "Diplomat" },
  { name: "Orbita5", status: "active", label: "Orbita5" },
  { name: "Magako", status: "active", label: "Magako" },
  { name: "Vest Inv", status: "active", label: "Vest Inv." },
  { name: "Svaneti", status: "active", label: "Svaneti" },
  { name: "Orbita1", status: "active", label: "Orbita1" },
  { name: "Orbita2", status: "inactive", label: "Orbita2" },
  { name: "Diplomat1", status: "inactive", label: "Diplomat1" },
  { name: "Orbita3", status: "inactive", label: "Orbita3" },
  { name: "Vest Inv1", status: "inactive", label: "Vest Inv1." },
  { name: "Orbita4", status: "inactive", label: "Orbita4" },
  { name: "Orbita6", status: "inactive", label: "Orbita6" },
  { name: "Kant1", status: "inactive", label: "Kant1" },
  { name: "Orbita7", status: "inactive", label: "Orbita7" },
  { name: "Magako1", status: "inactive", label: "Magako1" },
  { name: "Svaneti1", status: "inactive", label: "Svaneti1" },
];
